# Generated by Django 4.2.1 on 2024-05-10 11:40

from django.db import migrations, models
import django.db.models.deletion
import gestion_ville.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='filerecup',
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='demande_files/', validators=[gestion_ville.models.validate_file_extension])),
                ('filerecup', models.FileField(blank=True, upload_to='recup/', validators=[gestion_ville.models.validate_file_extension])),
                ('demande', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ville.demande')),
            ],
        ),
    ]
