# Generated by Django 4.2.1 on 2024-05-10 12:14

from django.db import migrations, models
import django.db.models.deletion
import gestion_ville.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0002_remove_demande_fichier_remove_demande_filerecup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='filerecup',
        ),
        migrations.AddField(
            model_name='fichier',
            name='citoyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ville.citoyen'),
        ),
        migrations.CreateModel(
            name='FichierRecup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filerecup', models.FileField(blank=True, upload_to='recup/', validators=[gestion_ville.models.validate_file_extension])),
                ('citoyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ville.citoyen')),
            ],
        ),
    ]
